--
-- PostgreSQL database dump
--

-- Dumped from database version 13.16 (Debian 13.16-1.pgdg120+1)
-- Dumped by pg_dump version 13.16 (Debian 13.16-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE ONLY public.producto_carrito DROP CONSTRAINT fkstfkowpwxp1ih2nj3f8gwetqd;
ALTER TABLE ONLY public.carrito DROP CONSTRAINT fkkg5h8ejijsgwfr68aoggh4l8m;
ALTER TABLE ONLY public.producto_carrito DROP CONSTRAINT fkht34thlww4903in1c6r1wmctl;
ALTER TABLE ONLY public.usuarios DROP CONSTRAINT usuarios_pkey;
ALTER TABLE ONLY public.carrito DROP CONSTRAINT uk1wsroe3wjs4dtnskxrlh7sm71;
ALTER TABLE ONLY public.productos DROP CONSTRAINT productos_pkey;
ALTER TABLE ONLY public.producto_carrito DROP CONSTRAINT producto_carrito_pkey;
ALTER TABLE ONLY public.carrito DROP CONSTRAINT carrito_pkey;
ALTER TABLE public.usuarios ALTER COLUMN id DROP DEFAULT;
DROP SEQUENCE public.usuarios_id_seq;
DROP TABLE public.usuarios;
DROP TABLE public.productos;
DROP TABLE public.producto_carrito;
DROP TABLE public.carrito;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: carrito; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.carrito (
    id bigint NOT NULL,
    precio_total double precision NOT NULL,
    id_usuario bigint NOT NULL
);


ALTER TABLE public.carrito OWNER TO iweb;

--
-- Name: carrito_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.carrito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto_carrito; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.producto_carrito (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario double precision NOT NULL,
    subtotal double precision NOT NULL,
    id_carrito bigint NOT NULL,
    id_producto bigint NOT NULL
);


ALTER TABLE public.producto_carrito OWNER TO iweb;

--
-- Name: producto_carrito_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.producto_carrito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_carrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.productos (
    id bigint NOT NULL,
    categoria character varying(255) NOT NULL,
    descripcion character varying(500) NOT NULL,
    foto character varying(255),
    nombre character varying(255) NOT NULL,
    precio double precision NOT NULL,
    stock integer NOT NULL
);


ALTER TABLE public.productos OWNER TO iweb;

--
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    administrador boolean NOT NULL,
    bloqueado boolean NOT NULL,
    email character varying(255) NOT NULL,
    fecha_nacimiento date,
    nombre character varying(255),
    password character varying(255)
);


ALTER TABLE public.usuarios OWNER TO iweb;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

CREATE SEQUENCE public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuarios_id_seq OWNER TO iweb;

--
-- Name: usuarios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: iweb
--

ALTER SEQUENCE public.usuarios_id_seq OWNED BY public.usuarios.id;


--
-- Name: usuarios id; Type: DEFAULT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.usuarios ALTER COLUMN id SET DEFAULT nextval('public.usuarios_id_seq'::regclass);


--
-- Data for Name: carrito; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.carrito (id, precio_total, id_usuario) FROM stdin;
2	0	9
1	667	4
3	56	2
\.


--
-- Data for Name: producto_carrito; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.producto_carrito (id, cantidad, precio_unitario, subtotal, id_carrito, id_producto) FROM stdin;
4	1	45	45	2	6
5	1	56	56	3	5
6	2	45	90	1	6
8	2	56	112	1	5
1	4	35	140	1	2
7	2	23	46	1	7
2	3	56	168	1	3
3	3	37	111	1	4
9	1	47	47	1	10
10	1	56	56	3	3
\.


--
-- Data for Name: productos; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.productos (id, categoria, descripcion, foto, nombre, precio, stock) FROM stdin;
2	hola	ddddddddddddddddddddd	bolso_puma_coperni.jpg	bolso puma coperni 	35	5
3	botas	ddddddddddddddddddddd	botas_futbol_ultra_5.jpg	botas futbol ultra 5	56	6
4	botas 	eeeeeeeeeeeeeeeee	botas_puma_evolve_niño.jpg	botas puma evolve niño	37	5
5	camiseta	eeeeeeeeeeeeeeeeeeeeeee	camiseta_ac_milan.jpg	camiseta ac milan	56	3
6	camiseta	ssssssssssssssssssssssssss	camiseta_manchester_city.jpg	camiseta machester city	45	3
7	camiseta	aaaaaaaaaaaaaaaaaa	camiseta_puma_rocket_league.jpg	camiseta puma rocket league	23	3
8	camiseta	erwgeeeeeeee	camiseta_pumaSquad_negra.jpg	camiseta puma squad negra	47	4
9	camiseta	ddddddddddddddddddddddddd	camiseta_skepta_blanca.jpg	camiseta skepta blanca	56	4
10	chaqueta	wdwwwwwwwwwwww	chaqueta_minicats_niños.jpg	chaqueta minicats niños	47	45
11	chaqueta	wfeeeeeeeeeeeeeeee	chaqueta_reversible_negra.jpg	chaqueta reversible negra	67	5
12	chaqueta	wwwwwwwwwwwwwwwwww	chaqueta_skepta_negra.jpg	chaqueta skepta negra	35	2
13	chaqueta	eeeeeeeeeeeeeeeeeeeeeeeeeeeee	chaqueta_verde_puma.jpg	chaqueta verde puma	35	5
\.


--
-- Data for Name: usuarios; Type: TABLE DATA; Schema: public; Owner: iweb
--

COPY public.usuarios (id, administrador, bloqueado, email, fecha_nacimiento, nombre, password) FROM stdin;
2	t	f	admin@gmail.com	1999-01-01	admin	admin
4	f	f	user@gmail.com	1997-01-01	user	user
6	f	f	user3@gmail.com	1999-01-01	user3	user3
7	f	f	user4@gmail.com	1900-01-01	user4	user4
8	f	f	user5@gmail.com	1990-01-01	user5	user5
9	f	f	user6@gmail.com	2004-02-01	user6	user6
5	f	f	user2@gmail.com	1999-01-01	user2	user2
\.


--
-- Name: carrito_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.carrito_id_seq', 3, true);


--
-- Name: producto_carrito_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.producto_carrito_id_seq', 10, true);


--
-- Name: productos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.productos_id_seq', 13, true);


--
-- Name: usuarios_id_seq; Type: SEQUENCE SET; Schema: public; Owner: iweb
--

SELECT pg_catalog.setval('public.usuarios_id_seq', 12, true);


--
-- Name: carrito carrito_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT carrito_pkey PRIMARY KEY (id);


--
-- Name: producto_carrito producto_carrito_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.producto_carrito
    ADD CONSTRAINT producto_carrito_pkey PRIMARY KEY (id);


--
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- Name: carrito uk1wsroe3wjs4dtnskxrlh7sm71; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT uk1wsroe3wjs4dtnskxrlh7sm71 UNIQUE (id_usuario);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: producto_carrito fkht34thlww4903in1c6r1wmctl; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.producto_carrito
    ADD CONSTRAINT fkht34thlww4903in1c6r1wmctl FOREIGN KEY (id_carrito) REFERENCES public.carrito(id);


--
-- Name: carrito fkkg5h8ejijsgwfr68aoggh4l8m; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT fkkg5h8ejijsgwfr68aoggh4l8m FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- Name: producto_carrito fkstfkowpwxp1ih2nj3f8gwetqd; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.producto_carrito
    ADD CONSTRAINT fkstfkowpwxp1ih2nj3f8gwetqd FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- PostgreSQL database dump complete
--

