--
-- PostgreSQL database dump
--

-- Dumped from database version 13.16 (Debian 13.16-1.pgdg120+1)
-- Dumped by pg_dump version 13.16 (Debian 13.16-1.pgdg120+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: carrito; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.carrito (
    id bigint NOT NULL,
    precio_total double precision NOT NULL,
    id_usuario bigint NOT NULL
);


ALTER TABLE public.carrito OWNER TO iweb;

--
-- Name: carrito_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.carrito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.carrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: producto_carrito; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.producto_carrito (
    id bigint NOT NULL,
    cantidad integer NOT NULL,
    precio_unitario double precision NOT NULL,
    subtotal double precision NOT NULL,
    id_carrito bigint NOT NULL,
    id_producto bigint NOT NULL
);


ALTER TABLE public.producto_carrito OWNER TO iweb;

--
-- Name: producto_carrito_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.producto_carrito ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.producto_carrito_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: productos; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.productos (
    id bigint NOT NULL,
    categoria character varying(255) NOT NULL,
    descripcion character varying(500) NOT NULL,
    foto character varying(255),
    nombre character varying(255) NOT NULL,
    precio double precision NOT NULL,
    stock integer NOT NULL
);


ALTER TABLE public.productos OWNER TO iweb;

--
-- Name: productos_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

ALTER TABLE public.productos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.productos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: usuarios; Type: TABLE; Schema: public; Owner: iweb
--

CREATE TABLE public.usuarios (
    id bigint NOT NULL,
    administrador boolean NOT NULL,
    bloqueado boolean NOT NULL,
    email character varying(255) NOT NULL,
    fecha_nacimiento date,
    nombre character varying(255),
    password character varying(255)
);


ALTER TABLE public.usuarios OWNER TO iweb;

--
-- Name: usuarios_id_seq; Type: SEQUENCE; Schema: public; Owner: iweb
--

CREATE SEQUENCE public.usuarios_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.usuarios_id_seq OWNER TO iweb;

--
-- Name: usuarios_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: iweb
--

ALTER SEQUENCE public.usuarios_id_seq OWNED BY public.usuarios.id;


--
-- Name: usuarios id; Type: DEFAULT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.usuarios ALTER COLUMN id SET DEFAULT nextval('public.usuarios_id_seq'::regclass);


--
-- Name: carrito carrito_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT carrito_pkey PRIMARY KEY (id);


--
-- Name: producto_carrito producto_carrito_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.producto_carrito
    ADD CONSTRAINT producto_carrito_pkey PRIMARY KEY (id);


--
-- Name: productos productos_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.productos
    ADD CONSTRAINT productos_pkey PRIMARY KEY (id);


--
-- Name: carrito uk1wsroe3wjs4dtnskxrlh7sm71; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT uk1wsroe3wjs4dtnskxrlh7sm71 UNIQUE (id_usuario);


--
-- Name: usuarios usuarios_pkey; Type: CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.usuarios
    ADD CONSTRAINT usuarios_pkey PRIMARY KEY (id);


--
-- Name: producto_carrito fkht34thlww4903in1c6r1wmctl; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.producto_carrito
    ADD CONSTRAINT fkht34thlww4903in1c6r1wmctl FOREIGN KEY (id_carrito) REFERENCES public.carrito(id);


--
-- Name: carrito fkkg5h8ejijsgwfr68aoggh4l8m; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.carrito
    ADD CONSTRAINT fkkg5h8ejijsgwfr68aoggh4l8m FOREIGN KEY (id_usuario) REFERENCES public.usuarios(id);


--
-- Name: producto_carrito fkstfkowpwxp1ih2nj3f8gwetqd; Type: FK CONSTRAINT; Schema: public; Owner: iweb
--

ALTER TABLE ONLY public.producto_carrito
    ADD CONSTRAINT fkstfkowpwxp1ih2nj3f8gwetqd FOREIGN KEY (id_producto) REFERENCES public.productos(id);


--
-- PostgreSQL database dump complete
--

